import React, { useEffect, useMemo, useState } from 'react';
import { authApi, createAdminApi } from './api.js';

const emptyProduct = { name: '', category: 'Makam Takımları', description: '', sku: '', status: 'active' };
const categories = ['Makam Takımları', 'Personel Masaları', 'Toplantı Masaları', 'Ofis Koltukları', 'Depolama Sistemleri'];

function Mark() {
  return <span className="admin-mark"><b>B</b><i></i><b>C</b></span>;
}

function Login({ onLogin }) {
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const submit = async (event) => {
    event.preventDefault(); setLoading(true); setError('');
    try { const result = await authApi.login(Object.fromEntries(new FormData(event.currentTarget))); onLogin(result.token); }
    catch (err) { setError(err.message); }
    finally { setLoading(false); }
  };
  return <section className="login-screen"><div className="login-art"><a className="admin-brand" href="/"><Mark/><span><strong>BAŞKENT CLASS</strong><small>YÖNETİM PANELİ</small></span></a><div className="login-message"><span className="gold-label">PREMIUM OFİS DENEYİMİ</span><h1>Markanızın<br/><em>kontrol merkezi.</em></h1><p>İçerik, ürün ve müşteri taleplerinizi tek ekrandan yönetin.</p></div><p className="login-copyright">© 2026 Başkent Class Büro</p></div><div className="login-panel"><form className="login-form" onSubmit={submit}><span className="login-index">YÖNETİCİ GİRİŞİ / 01</span><h2>Tekrar hoş geldiniz.</h2><p>Yönetim paneline devam etmek için bilgilerinizi girin.</p><label>Kullanıcı adı<input name="username" defaultValue="admin" required/></label><label>Şifre<input name="password" type="password" defaultValue="class2026" required/></label><p className="login-error">{error}</p><button className="gold-button" disabled={loading}>{loading ? 'Giriş yapılıyor…' : 'Giriş yap'} <span>→</span></button><div className="demo-credentials"><strong>Demo erişim</strong><span>Kullanıcı: admin</span><span>Şifre: class2026</span></div><small className="security-note">Giriş artık backend tarafından doğrulanır. Üretimde AUTH_SECRET ve ADMIN_PASSWORD ortam değişkenlerini değiştirin.</small></form></div></section>;
}

function Dashboard({ data, go }) {
  const metrics = [
    ['✉','Toplam Talep',data.totalInquiries,'Form ve WhatsApp talepleri'],['◉','Yeni Talepler',data.newInquiries,'Geri dönüş bekliyor'],['▦','Aktif Ürün',data.activeProducts,'Sitede görünür'],['✓','Tamamlanan',data.completedInquiries,'Sonuçlanan talepler']
  ];
  return <><div className="welcome-card"><div><span className="gold-label">HOŞ GELDİNİZ</span><h2>İyi günler,<br/><em>Başkent Class.</em></h2><p>Sitenizin güncel durumunu ve son müşteri hareketlerini buradan takip edebilirsiniz.</p></div><a href="/" target="_blank">Canlı siteyi aç <span>↗</span></a></div><div className="metric-grid">{metrics.map(item=><article className="metric-card" key={item[1]}><span className="metric-icon">{item[0]}</span><p>{item[1]}</p><strong>{item[2] ?? 0}</strong><small><i></i>{item[3]}</small></article>)}</div><div className="dashboard-grid"><article className="panel-card"><div className="panel-head"><div><span>SON HAREKETLER</span><h3>Gelen Talepler</h3></div><button className="text-button" onClick={()=>go('inquiries')}>Tümünü gör →</button></div>{data.recentInquiries?.length ? <div className="table-wrap"><table><thead><tr><th>Müşteri</th><th>Ürün</th><th>Durum</th><th>Tarih</th></tr></thead><tbody>{data.recentInquiries.map(item=><tr key={item.id}><td>{item.name}<small>{item.phone}</small></td><td>{item.product}</td><td><span className={`status-pill ${item.status==='Tamamlandı'?'done':''}`}>{item.status}</span></td><td>{formatDate(item.createdAt)}</td></tr>)}</tbody></table></div>:<div className="empty-state show"><span>✉</span><p>Henüz bir talep bulunmuyor.</p><small>İletişim formu kullanıldığında burada görünecek.</small></div>}</article><article className="panel-card quick-card"><div className="panel-head"><div><span>HIZLI ERİŞİM</span><h3>Site Yönetimi</h3></div></div>{[['content','Aa','Hero içeriğini düzenle','Ana sayfa başlık ve açıklama'],['products','＋','Yeni ürün ekle','Koleksiyonu güncelle'],['settings','⚙','İletişim ayarları','Telefon ve WhatsApp']].map(item=><button key={item[0]} onClick={()=>go(item[0])}><span className="quick-icon">{item[1]}</span><span><strong>{item[2]}</strong><small>{item[3]}</small></span><b>→</b></button>)}</article></div></>;
}

function ContentEditor({ settings, save }) {
  const [form, setForm] = useState(settings);
  useEffect(()=>setForm(settings),[settings]);
  const field = (name) => ({ name, value: form[name] || '', onChange: e=>setForm({...form,[name]:e.target.value}) });
  return <><div className="view-intro"><div><span className="gold-label">SİTE İÇERİĞİ</span><h2>Ana sayfanızı yönetin.</h2><p>Kaydedilen değişiklikler API üzerinden canlı siteye yansır.</p></div><a className="outline-button" href="/" target="_blank">Önizle ↗</a></div><form className="editor-layout" onSubmit={e=>{e.preventDefault();save(form);}}><div className="editor-card"><div className="editor-head"><span>01</span><div><h3>Karşılama Alanı</h3><p>Ana sayfanın ilk görünen başlık ve mesajları</p></div></div><label>Üst etiket<input {...field('heroEyebrow')}/></label><div className="form-grid three"><label>Başlık<input {...field('heroLine')}/></label><label>Gold vurgu<input {...field('heroHighlight')}/></label><label>Devam metni<input {...field('heroSuffix')}/></label></div><label>Açıklama<textarea rows="4" {...field('heroDescription')}/></label></div><div className="editor-card"><div className="editor-head"><span>02</span><div><h3>Öne Çıkan Ürün</h3><p>Vera ürün alanındaki metinler</p></div></div><label>Seri adı<input {...field('featuredSeries')}/></label><div className="form-grid"><label>Başlık<input {...field('featuredLine')}/></label><label>Gold vurgu<input {...field('featuredHighlight')}/></label></div><label>Açıklama<textarea rows="4" {...field('featuredDescription')}/></label></div><div className="sticky-actions"><span>Değişiklikler backend’e kaydedilir</span><button className="gold-button">Değişiklikleri kaydet <span>→</span></button></div></form></>;
}

function Products({ products, api, reload, notify }) {
  const [editing,setEditing]=useState(emptyProduct); const [search,setSearch]=useState('');
  const shown=products.filter(item=>`${item.name} ${item.sku}`.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')));
  const submit=async e=>{e.preventDefault();try{editing.id?await api.updateProduct(editing.id,editing):await api.createProduct(editing);setEditing(emptyProduct);await reload();notify('Ürün kaydedildi.');}catch(err){notify(err.message);}};
  const remove=async()=>{if(!editing.id||!confirm('Bu ürün silinsin mi?'))return;await api.deleteProduct(editing.id);setEditing(emptyProduct);await reload();notify('Ürün silindi.');};
  return <><div className="view-intro"><div><span className="gold-label">KOLEKSİYON</span><h2>Ürünleri yönetin.</h2><p>Aktif ürünler canlı sitedeki koleksiyon alanında görünür.</p></div><button className="gold-button" onClick={()=>setEditing(emptyProduct)}>Yeni ürün <span>＋</span></button></div><div className="product-layout"><div className="product-list-card"><div className="list-toolbar"><label className="search-box"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ürün ara"/></label></div><div className="product-list">{shown.map(item=><article className="product-row" key={item.id}><div className="product-thumb"></div><div><strong>{item.name}</strong><small>{item.sku}</small></div><span>{item.category}</span><span className={`status-pill ${item.status==='active'?'done':''}`}>{item.status==='active'?'Aktif':'Taslak'}</span><div className="row-actions"><button onClick={()=>setEditing(item)}>✎</button></div></article>)}</div></div><form className="product-editor" onSubmit={submit}><div className="panel-head"><div><span>{editing.id?'ÜRÜN DÜZENLEME':'YENİ KAYIT'}</span><h3>{editing.id?editing.name:'Ürün ekle'}</h3></div></div><label>Ürün adı<input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Kategori<select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>Kısa açıklama<textarea rows="3" value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><div className="form-grid"><label>Ürün kodu<input value={editing.sku} onChange={e=>setEditing({...editing,sku:e.target.value})}/></label><label>Durum<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="active">Aktif</option><option value="draft">Taslak</option></select></label></div><button className="gold-button">Ürünü kaydet <span>→</span></button>{editing.id&&<button type="button" className="danger-button" onClick={remove}>Ürünü sil</button>}</form></div></>;
}

function Inquiries({ inquiries, api, reload, notify }) {
  const [filter,setFilter]=useState('all'); const shown=filter==='all'?inquiries:inquiries.filter(i=>i.status===filter);
  const update=async(id,status)=>{await api.updateInquiry(id,status);await reload();notify('Talep güncellendi.');};
  const remove=async id=>{if(!confirm('Talep silinsin mi?'))return;await api.deleteInquiry(id);await reload();notify('Talep silindi.');};
  return <><div className="view-intro"><div><span className="gold-label">MÜŞTERİ TALEPLERİ</span><h2>İletişimi takip edin.</h2><p>Form üzerinden gelen başvuruları durumlarına göre yönetin.</p></div></div><div className="inquiry-toolbar"><div className="filter-tabs">{['all','Yeni','Görüşüldü','Tamamlandı'].map(item=><button className={filter===item?'active':''} onClick={()=>setFilter(item)} key={item}>{item==='all'?'Tümü':item}</button>)}</div></div><div className="inquiry-list">{shown.map(item=><article className="inquiry-card" key={item.id}><div><h3>{item.name}</h3><p><a href={`tel:${item.phone}`}>{item.phone}</a></p></div><div><p><strong>{item.product}</strong><br/>{item.message||'Mesaj belirtilmedi.'}</p></div><div><time>{formatDate(item.createdAt)}</time><select value={item.status} onChange={e=>update(item.id,e.target.value)}><option>Yeni</option><option>Görüşüldü</option><option>Tamamlandı</option></select></div><button className="delete-inquiry" onClick={()=>remove(item.id)}>×</button></article>)}</div>{!shown.length&&<div className="large-empty show"><span>✉</span><h3>Henüz talep yok</h3><p>Ana sitedeki formdan gelen başvurular burada listelenecek.</p></div>}</>;
}

function Settings({ settings, save, reset }) {
  const [form,setForm]=useState(settings); useEffect(()=>setForm(settings),[settings]);
  const field=name=>({value:form[name]||'',onChange:e=>setForm({...form,[name]:e.target.value})});
  return <><div className="view-intro"><div><span className="gold-label">SİSTEM AYARLARI</span><h2>Marka bilgileri.</h2><p>Telefon ve mesajlaşma bilgilerini tek noktadan güncelleyin.</p></div></div><form className="settings-grid" onSubmit={e=>{e.preventDefault();save(form);}}><div className="editor-card"><div className="editor-head"><span>01</span><div><h3>Firma Bilgileri</h3><p>Sitede kullanılan temel marka bilgileri</p></div></div><label>Firma adı<input {...field('companyName')}/></label><label>Telefon görünümü<input {...field('phoneDisplay')}/></label><label>Telefon bağlantısı<input {...field('phoneRaw')}/></label><label>WhatsApp numarası<input {...field('whatsapp')}/></label><button className="gold-button">Ayarları kaydet <span>→</span></button></div><div className="editor-card backup-card"><div className="editor-head"><span>02</span><div><h3>Veri ve Yedek</h3><p>Sunucudaki varsayılan verileri yönetin</p></div></div><div className="backup-row danger-zone"><div><strong>İçerik ve ürünleri sıfırla</strong><small>Müşteri talepleri korunur.</small></div><button type="button" className="danger-button" onClick={reset}>Sıfırla</button></div><p className="backend-note"><span>i</span><strong>Backend veri modu</strong> Bilgiler artık Express API üzerinden sunucudaki JSON veri deposunda saklanır.</p></div></form></>;
}

const formatDate=value=>new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value));

export default function Admin() {
  const [token,setToken]=useState(()=>sessionStorage.getItem('bc_api_token')||''); const [view,setView]=useState('dashboard');
  const [dashboard,setDashboard]=useState({}); const [settings,setSettings]=useState({}); const [products,setProducts]=useState([]); const [inquiries,setInquiries]=useState([]); const [toast,setToast]=useState(''); const [menu,setMenu]=useState(false);
  const api=useMemo(()=>createAdminApi(token),[token]);
  const notify=message=>{setToast(message);setTimeout(()=>setToast(''),2500);};
  const load=async()=>{try{const [d,s,p,i]=await Promise.all([api.dashboard(),api.settings(),api.products(),api.inquiries()]);setDashboard(d);setSettings(s);setProducts(p);setInquiries(i);}catch(err){if(err.message.toLowerCase().includes('oturum'))logout();else notify(err.message);}};
  useEffect(()=>{if(token)load();},[token]);
  const login=value=>{sessionStorage.setItem('bc_api_token',value);setToken(value);}; const logout=()=>{sessionStorage.removeItem('bc_api_token');setToken('');};
  if(!token)return <Login onLogin={login}/>;
  const titles={dashboard:'Genel Bakış',content:'Site İçeriği',products:'Ürünler',inquiries:'Talepler',settings:'Ayarlar'};
  const saveSettings=async data=>{try{const saved=await api.saveSettings(data);setSettings(saved);notify('Değişiklikler kaydedildi.');}catch(err){notify(err.message);}};
  const reset=async()=>{if(!confirm('İçerik ve ürünler sıfırlansın mı?'))return;await api.reset();await load();notify('Varsayılan veriler yüklendi.');};
  return <div className="admin-shell"><aside className={`sidebar ${menu?'open':''}`}><a className="admin-brand" href="/"><Mark/><span><strong>BAŞKENT CLASS</strong><small>YÖNETİM PANELİ</small></span></a><nav className="admin-nav">{[['dashboard','⌂','Genel Bakış'],['content','◇','Site İçeriği'],['products','▦','Ürünler'],['inquiries','✉','Talepler'],['settings','⚙','Ayarlar']].map(item=><button className={`nav-item ${view===item[0]?'active':''}`} onClick={()=>{setView(item[0]);setMenu(false);}} key={item[0]}><span className="nav-icon">{item[1]}</span><span>{item[2]}</span>{item[0]==='inquiries'&&<b>{dashboard.newInquiries||0}</b>}</button>)}</nav><div className="sidebar-bottom"><a href="/" target="_blank"><span>↗</span> Siteyi görüntüle</a><button onClick={logout}><span>⇥</span> Çıkış yap</button></div></aside><main className="admin-main"><header className="admin-header"><button className="sidebar-toggle" onClick={()=>setMenu(!menu)}><span></span><span></span></button><div><p>YÖNETİM PANELİ</p><h1>{titles[view]}</h1></div><div className="header-actions"><a className="icon-button" href="/" target="_blank">↗</a><div className="admin-profile"><span>BC</span><div><strong>Yönetici</strong><small>API bağlı</small></div></div></div></header><div className="admin-content"><section className="admin-view active">{view==='dashboard'&&<Dashboard data={dashboard} go={setView}/>} {view==='content'&&<ContentEditor settings={settings} save={saveSettings}/>} {view==='products'&&<Products products={products} api={api} reload={load} notify={notify}/>} {view==='inquiries'&&<Inquiries inquiries={inquiries} api={api} reload={load} notify={notify}/>} {view==='settings'&&<Settings settings={settings} save={saveSettings} reset={reset}/>}</section></div></main><div className={`admin-toast ${toast?'show':''}`}>{toast}</div></div>;
}
